name: Makefile CI

on:
  push:
    branches: [ "liberatedsystems-master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v2

    - name: Install dependencies
      run: make ep

    - name: Compile ESP32
      run: make firmware-heltec32_v3

    - name: Compile nRF52
      run: make firmware-rak4631
