name: Makefile CI

on:
  push:
    branches: [ "liberatedsystems-master" ]

  workflow_dispatch:
    inputs:
      verbose_make:
        description: 'Verbose Makefile output'
        type: boolean
        default: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v2

    - name: Cache Arduino Cores
      uses: actions/cache@v6
      with:
        path: ~/.arduino15
        key: ${{ runner.os }}-arduino15-${{ hashFiles('**/platform.local.txt') }}
        restore-keys: |
          ${{ runner.os }}-arduino15-

    - name: Update Arduino Core Index
      run: make prep-index
      # issue: https://github.com/liberatedsystems/RNode_Firmware_CE/issues/125
      continue-on-error: true

    - name: Install dependencies
      run: make prep

    - name: Rename INO workaround
      run: mv RNode_Firmware_CE.ino microReticulum_Firmware.ino

    - name: Compile ESP32
      run: make firmware-heltec32_v3 ${{ github.event.inputs.verbose_make == 'false' && 'V=0' || 'V=1' }}

    - name: Compile nRF52
      run: make firmware-rak4631 ${{ github.event.inputs.verbose_make == 'false' && 'V=0' || 'V=1' }}

    - name: Archive firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rak4631
        path: |
          build/rakwireless.nrf52.WisCoreRAK4631Board/microReticulum_Firmware.ino.zip

    - name: Archive firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: heltec32_v3
        path: |
          build/esp32.esp32.heltec_wifi_lora_32_V3/microReticulum_Firmware.ino.bin
          build/esp32.esp32.heltec_wifi_lora_32_V3/microReticulum_Firmware.ino.bootloader.bin
          build/esp32.esp32.heltec_wifi_lora_32_V3/microReticulum_Firmware.ino.partitions.bin


