name: Makefile CI

on:
  push:
    branches: [ "liberatedsystems-master" ]

  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v2

    - name: Install dependencies
      run: make prep

    - name: Compile ESP32
      run: make firmware-heltec32_v3

    - name: Compile nRF52
      run: make firmware-rak4631
